/**
 * Created by jayyu on 2015/10/29.
 */
var jsonData = [
    {
        "heading":"微信矩阵",
        "profile":"由大浙网官微等13个微信号组成的大浙网微信矩阵，拥有百万级粉丝。",
        "icon":"icon_wechat",
        "open":[
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic1.jpg",
                        "details":"腾讯大浙网"
                    }
                ],
                "info":"<p>ID：Zhelilehuo </p><p>浙江第一手资讯+吃喝玩乐攻略。各种有用、有趣、有品的资讯，赶紧关注我吧。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic2.jpg",
                        "details":"大浙汽车"
                    }
                ],
                "info":"<p>ID：zjqqauto</p><p>这里有最实用的养车干货，教你轻松省钱；有最吊炸天的开车故事，能让你学到很多路上的经验；开车在路上，别再傻乎乎的，赶紧关注我们，学习如何做一个成功的车主吧！</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic3.jpg",
                        "details":"杭州美食惠"
                    }
                ],
                "info":"<p>ID：foodhz</p><p>这里是全杭城最好玩的吃货集中营！如果你是文艺的吃货，我们会为你奉上为你量身定制的美食视频；如果你是吃货中的行动派，我们的主页君小美能带你吃遍全城；如果你初到杭州还对杭州不太熟悉，我们会为你送上杭城最全的吃货地图，川、陕、粤…各大菜系全都不是事儿～寂寞时，还能与最任性的主页君聊聊天，简直棒呆啦！</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic4.jpg",
                        "details":"浙fashion"
                    }
                ],
                "info":"<p>ID：zhefashion</p><p>高大上与接地气随时勾搭，推荐浙江本地第一手时尚消费资讯及粉丝福利活动，请随身携带您手机里的移动时尚手册，我们就是爱血拼、爱美丽、爱折腾，根本停不下来！</p>"
            },{
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic5.jpg",
                        "details":"机智哥"
                    }
                ],
                "info":"<p>ID：jizgqq</p><p>想要了解第一手数码家电资讯吗？想要知道苹果什么时候发布新品吗？买了新手机却不知道怎么更好地使用吗？玩腻了手机里的APP却找不到其他更好玩的吗？关注“机智哥”，告别只能看着别人玩的日子。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic6.jpg",
                        "details":"大浙家居"
                    }
                ],
                "info":"<p>ID：dazhejiaju</p><p>还在忧虑装修知识完全不懂，根本不知怎么下手？还在担心装修被坑，拼死拼活却是为装修公司挣钱？还在害怕质量不过关，没住几天就问题百出？亲，你莫担心，有我在呢！关注，大浙家居，你24小时的私人装修顾问马上签约。家居君我优点不多，就是知识特别专业，咨讯特别新鲜，案例特别丰富，互动特别热情。四陪服务，满意贴心。小指一点，快来找我吧！</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic7.jpg",
                        "details":"大浙健康"
                    }
                ],
                "info":"<p>大浙健康</p><p>健康资讯第一站，每天推送纯干货，这里有超过百位名医做后援，拨开真假难辨的养生迷雾，解答羞于开口的两性疑惑，你负责订阅，我们负责求真。一生只活一次，必须健康地活。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic8.jpg",
                        "details":"大浙结婚"
                    }
                ],
                "info":"<p>ID：zjwedding</p><p>这里的帅哥春心荡漾，这里的美女望穿秋水。这里有最热闹的相亲会，助你邂逅爱情；这里有最前沿的结婚资讯，菜鸟也能变达人。大浙结婚做你身边最佳的一站式结婚筹备平台。</p>"
            },{
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic9.jpg",
                        "details":"大浙教育"
                    }
                ],
                "info":"<p>ID：dazhejiaoyu</p><p>在这里，我们每天发布最新的教育资讯，分享先进的教育教学理念，为学校、父母、孩子提供高品质互动体验。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic10.jpg",
                        "details":"浙江家长汇"
                    }
                ],
                "info":"<p>ID：dazheqz</p><p>浙江家长汇是腾讯大浙网亲子频道官方微信号，每天为您提供最权威的亲子活动推荐、育儿知识、健康指导、育儿知识等，做宝宝家长最贴心的朋友。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic11.jpg",
                        "details":"乐享宁波"
                    }
                ],
                "info":"<p>ID：dazhenb</p><p>大浙网宁波专属官微，传递宁波当地最需要知道的新鲜事儿，掌握各种潮流资讯，简单互动就有各种丰厚福利领取，管理员除了随意调戏还能通过关系网尽力帮助你们解决大小问题，如果你想从一个宁波人，变成一个“懂很多”的宁波人，那么请别犹豫，和我们一起读懂宁波分享乐趣！</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic12.jpg",
                        "details":"穷游目的地"
                    }
                ],
                "info":"<p>ID：poptrip_qq</p><p>如果你喜爱旅游，推荐你一个靠谱实用的公众账号：穷游目的地。每天推荐纯干货：各大城市、国家的实用攻略，好玩又小众的旅行地推荐、出游省钱技巧等等…重点，经常会有免费旅游活动哦，保证没有猫腻！对了，这个账号的主页菌简直就是业界最有良心的，基本有问必答，就连单身狗都还帮忙介绍对象~</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/1_pic13.jpg",
                        "details":"腾讯房产杭州站"
                    }
                ],
                "info":"<p>ID：hzhouse</p><p>尊贵的小主，你现在即将看到的就是杭州史上逼格最高的房地产微信公众号咯！在这里你可能会被最实用的买房知识砸晕，也可能被最具时效性的资讯包围。随时随地，做你买房、卖房、租房的私人秘书。</p>"
            }
        ]
    },
    {
        "heading":"Tips消息推送",
        "profile":"Tips推送功能将重要咨询第一时间传递给用户。",
        "icon":"icon_tips",
        "open":[
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/2_pic1.jpg",
                        "details":"TIPS"
                    }
                ],
                "info":"<p>TIPS是大浙网在PC端的拳头产品，以最快的速度、精确的准度和超高的触达率，把资讯推送给浙江省内的在线QQ用户。其区域定向推送功能，是内容本地化运营的一把利器。</p>"
            }
        ]
    },
    {
        "heading":"QQ迷你首页",

        "profile":"QQ迷你页帮助浙江3200万QQ用户第一时间获取最新鲜、最好玩的信息",
        "icon":"icon_mini",
        "open":[
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/3_pic1.jpg",
                        "details":"QQ迷你首页"
                    }
                ],
                "info":"<p>腾讯网迷你页是腾讯用户在登录QQ后自动弹出的新闻页面，内容包括新闻、娱乐、财经等各行业资讯，帮助浙江3200万QQ用户第一时间获取最新鲜、最好玩的信息。</p>"
            }
        ]
    },
    {
        "heading":"腾讯新闻APP",
        "profile":"截止到2016年6月，腾讯新闻APP浙江页卡日均浏览量达6500万，日均独立访问用户数达630万",
        "icon":"icon_app",
        "open":[
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/4_pic1.jpg",
                        "details":"腾讯新闻APP"
                    },
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/4_pic2.jpg",
                        "details":"腾讯新闻APP"
                    },
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/4_pic3.jpg",
                        "details":"腾讯新闻APP"
                    },
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/4_pic4.jpg",
                        "details":"腾讯新闻APP"
                    },
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/4_pic5.jpg",
                        "details":"腾讯新闻APP"
                    },
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/4_pic6.jpg",
                        "details":"腾讯新闻APP"
                    },
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/4_pic7.jpg",
                        "details":"腾讯新闻APP"
                    }
                ],
                "info":"依托腾讯得天独厚的渠道优势，大浙网目前在移动端运营两款拥有海量用户的新闻APP产品：腾讯新闻客户端APP浙江页卡，及基于先进算法的智能APP“天天快报”的本地页卡。在无线端，我们同样拥有类似于PC端TIPS的信息推送工具——PUSH。"
            }
        ]
    },
    {
        "heading":"大浙网PC端",
        "profile":"截止到2016年6月， PC端日均浏览量达3300万，独立访问用户数达330万。",
        "icon":"icon_pc",
        "open":[
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/5_pic1.jpg",
                        "details":"大浙网PC端"
                    }
                ],
                "info":"<p>大浙网拥有覆盖浙江的新媒体产品矩阵，以及成熟的运营团队，这种优势在突发新闻及动态新闻的推送中被发挥得淋漓尽致。</p><p>2015年7月11日，台风“灿鸿”登陆浙江，大浙网在移动端和PC端推出全媒体直播。有700多万人通过腾讯新闻APP浙江页卡“玫瑰直播”页面了解“灿鸿”的最新动态，290多万人观看了浙江页卡推送的最新视频；网友跟帖达3.7万多条。另有100多万人通过电脑观看了大浙网的直播。</p>"
            }
        ]
    },
    {
        "heading":"大型活动策划及执行",
        "profile":"事件营销、整合商业及传播资源、强大的网友号召能力",
        "icon":"icon_activity",
        "open":[
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic1.jpg",
                        "details":"S女郎"
                    }
                ],
                "info":"<p>2013年7月，S女郎比赛线上报名人数达684人。长达3个月的活动，共计线下活动7场，合计曝光约1W人次。浙江地区各媒体，包括腾讯大浙网、杭州电视台、微微生活家、钱江晚报、淘女郎、青年时报、浙江在线、FM107等多家主流媒体同步合作支持。同时，S女郎活动与新丝路华东赛区进行了密切合作，大浙网作为“指定合作网络媒体”，拥有大赛专设奖项“腾讯大浙网网络模特专场”、“腾讯大浙网单项奖”。</p><p>活动在商超行业引起较大反响。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic2.jpg",
                        "details":"华东政务微博峰会"
                    }
                ],
                "info":"<p>2013年10月19日，2013年华东政务微博论坛在浙江湖州安吉成功举办。会议邀请了部分政府微博达人和知名学者，同时邀请了包括上海发布、南京发布、黑板报、孙警官说事等政务优秀微博运营部门负责人共计240余人，其中浙江区域60余人，华东区域180余位嘉宾到场，围绕“微言大义、舆通政和”以及“集结正能量”等主题进行高端对话，现场碰撞智慧火花，政务微博何去何从，如何引导大V发挥正能量，政府官员面对舆情如何发声等，都进入了讨论范围，会场参与积极踊跃，全天会议还进行了微博上墙，滚动播报。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic3.jpg",
                        "details":"大浙网一周年网络峰会"
                    }
                ],
                "info":"<p>2013年12月，大浙网2013浙江影响力网络盛典，以网络的形式重构进化论，从变化多端的互联网环境中寻求进化，对浙江的重大事件及热点人物进行评选，并对营销创新及效果转化的优秀案例进行颁奖。</p><p>会上输出2013年度十大浙江偶像、十大公众微信、十大政务微博、五大公益微博以及《浙江网民心理研究报告》，对浙江互联网发展趋势进行深度探讨，也为社会正能量的传播注入活力。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic4.jpg",
                        "details":"新年新衣"
                    }
                ],
                "info":"<p>2014年2月，新年新衣活动联合了包括浙江日报、钱江晚报、浙江电视台钱江都市频道、杭州电视台生活频道等多家一线媒体的共同参与，同时还和温州都市报、宁波广电网、永康日报等多家县市级媒体达成了联动合作。本次活动，总共参与媒体数达到了15家，全省筹集衣物30000余件，动员高校社区媒体织围巾8000余条，线下捐赠活动20余场，新闻报道50余篇。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic6.jpg",
                        "details":"2014中国城市力量盛典"
                    }
                ],
                "info":"<p> 2014年12月，“2014中国城市力量颁奖盛典”借助腾讯网全国区域门户、腾讯基金、腾讯公益等力量，整合浙江省委宣传部网信办、山东航空、米兰世博会、杭州歌舞剧院等各方面资源，面向全国腾讯网友，面向浙江省各地市政务官员，打开了圈层影响力、政务影响力双赢的局面。 </p><p>为15年大浙政务拓展打下了良好的基础，在政务圈层内塑造了优秀的品牌形象； </p><p>是腾讯各事业群跨界合作的一次典范，值得深入思考和后续延伸；通过区域门户全国互动，是在腾讯OMG事业部全国影响力提升的一次盛会； </p><p>活动借力杭州歌舞剧院，是一场公益与艺术结合的视觉盛宴； 峰会盛典有定制、有点亮、有水精灵、有丝绸，是创新创意的盛典；</p><p>大浙网2周年，润物细无声的植入，成就了大浙良好的品牌形象。 </p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic7.jpg",
                        "details":"郎郎：音为爱 公益演奏音乐会"
                    }
                ],
                "info":"<p>2015年1月，腾讯大浙网邀请世界级音乐大师郎郎，到杭州进行公益演出；</p><p> 通过征集，郎郎现场与100多名有音乐梦想的孩子进行同台演奏；</p><p>为十多名无妈乡的有梦想的贫困儿童征集“帮扶”妈妈，在现场，郎郎演奏，孩子们集体演唱《虫儿飞》，感动了现场上万名观众。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic8.jpg",
                        "details":"微信公开课  微信开发者培训班"
                    }
                ],
                "info":"<p>腾讯大浙网与微信团队合作，在杭州、宁波等地举办微信公开课：</p><p>2014年6月 第一季微信公开课在杭州浙大永谦剧场举办、报名8000人次，通知到场2000余人； </p><p>2014年10月第二季微信公开课在杭州世贸会展中心举办、报名6000人次，通知到场1000余人；</p><p>2015年5月，微信开发者大会在杭州举办，来自全国各地的微信开发爱好者到杭州接受微信官方培训； </p><p>2015年5月28日，第三季微信公开课在宁波大剧院举办，报名5000人次，通知到场1500余人；</p><p>2015年9月，微信公开课第四季再次落地杭州。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic5.jpg",
                        "details":"中国好声音第3季 第4季浙江招募平台 "
                    }
                ],
                "info":"<p>好声音第四季网络招募浙江总决选，一共2万多网友报名参加，不仅有来自温州的、宁波的、绍兴的、金华、嘉兴等省内各地的，还有来自南京、大连等地区的选手。</p><p>本季好声音线下一共活动举办了15场，投票参与人数达到300多万，经过全省网络投票、部分地市线下pk活动，最终选拔出浙江三强。</p><p>5月23浙江赛区总决选落地举行，共50名选手，300名大众粉丝团到场。选出浙江赛区总冠军，推送到全国导演组面试。</p><p>招商覆盖房产、商超、家电、珠保等行业。行业影响力较大。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic9.jpg",
                        "details":"互联网+旅游峰会 "
                    }
                ],
                "info":"<p>2015年8月11日，在腾讯总部及国家级和省级旅游部门的支持下，大浙网成功举办了“互联网+旅游”峰会</p><p>活动进一步促进大浙旅游营销行业的影响力；</p><p>获得了各地市旅游景区各部门的高度认同； </p><p>获得了各地市旅游景区各部门的高度认同；</p><p>为大浙旅游的下一步打下了坚实的基础；</p><p>使用酷炫的互联网元素提升了品牌和会务的整体格调。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic10.jpg",
                        "details":"浙江省全国科普日"
                    }
                ],
                "info":"<p>2015年9月，通过省科协指导、教育、科技、经信等部门支持，嘉兴市助力，桐乡县全力执行，大浙网承办了2015年科普日活动，800人与会，上万人互动。</p><p>本活动招募24个科技企业展览，5个科技行业CEO交流创新创业经历，选择互联网传播，互联网分享，无论在前期宣传还是在现场互动亦或者是后期制作，都大胆地结合互联网宣传科学，走在科普工作前沿。</p>"
            },
            {
                "imgList":[
                    {
                        "img":"http://mat1.gtimg.com/zj/yuwanli/brand/images/6_pic11.jpg",
                        "details":"腾讯大浙网3周年智慧嘉年华"
                    }
                ],
                "info":"<p>2015年11月，腾讯大浙网3周年智慧嘉年华，嫁接在ADM亚洲设计论坛中的一场最酷炫的智慧生活产品体验盛典。最大程度地结合腾讯优势资源，将QQ物联和微信生态链进行了挖掘，力求呈现出一场充分体现科技元素、体验优越、创意创新的非凡生活展。</p><p>2000平米的展会面积，将融合众多创意设计和创新科技，为广大腾讯大浙网网友提供一次智慧与互联网结合的狂欢。</p>"
            }
        ]
    }
];/*  |xGv00|3d197b77874f38d9684344d090bdc7a4 */